export const QUOTES = {
  text: [
    "My life has been a lie! God is dead! The government's lame! Thanksgiving is about killing Indians! Jesus wasn't born on Christmas! They moved the date, it was a pagan holiday!",
    "And this is why you don't invite a Floopy Doop and a Shmoopy Doop to the same party.",
    "Rick: Alright, Morty, I just gotta erhp combine it with some of your DNA.\n\nMorty: Oh well, okay. [unzips]\n\nRick: A hair, Morty. I need one of your hairs. This isn't Game of Thrones.",
    "Get off the high road, Summer! We all got pinkeye because you won't stop texting on the toilet.",
    "No, no, I haven't seen that. I mean, why would a Pop-Tart want to live inside a toaster, Rick? I mean, th-that would be like the scariest place for them to live. Y'know what I mean?",
    "That's because losers look stuff up while the rest of us are carp'en all them 'diems.",
    "All I have are pictures are of me and my friends from school. What? What teenage girl has pictures of her family? It's not like we're Mormon or dying",
    "To live is to risk it all, otherwise you're just an inert chunk of randomly assembled molecules drifting wherever the universe blows you.",
    "Morty: So what?! Y-Y-You could do things inside! Y-You could play guitar, you could masturbate!\n\nMorty Jr.: I don't wanna masturbate! I wanna conquer the planet!",
    "Nobody exists on purpose, nobody belongs anywhere, everybody's gonna die. Come watch TV.",
    "Well, all is forgiven, because right now, I’ve got an erection the size of an East Coast lighthouse, and I’m coming home to share it with my beautiful wife.",
    "Beth: When two people create a life together, they set aside their previous lives as individuals.\n\nJerry: Gimme a break! We're not heroes for having unprotected sex on prom night.",
    "I'm Doctor Who in this motherfucker! I could be a clone! I could be a hologram! We could clones controlled by robots controlled by special headsets that the real Rick and Morty are wearing while they're fucking your mother!",
    "Ambassador: Mr. Smith, Shrimply Pibbles' life can be saved... if we replace his heart with your human penis.\n\nJerry: I see... Wait, what?!",
    "The universe is a little too big to care about something so small.",
    "I'M A PICKLE! I'm pickle Riiiiiick!",
    "Stupid-ass, fart-saving, carpet-store motherfucker.",
    "Beth: Am I evil?\n\nRick: Worse, you're smart. When you know nothing matters, the universe is yours. And I've never met a universe that was into it. The universe is basically an animal, it grazes on the ordinary. It creates infinite idiots, just to eat them, not unlike your friend Timmy.",
    "Don't break an arm jerking yourself off, Morty.",
    "TO GET R*ugghhb*IGGITY RIGGITY WRECKED SOONN",
    "Come on, flip the pickle, Morty. You're not gonna regret it. The payoff is huge. I turned myself into a pickle, Morty! Boom! Big reveal! I'm a pickle! What do you think about that? I turned myself into a pickle! W-what are you just staring at me for, bro? I turned myself into a pickle, Morty.",
    "Mr. President, if I've learned one thing today, it's that sometimes you have to not give a fuck!",
    "Wait for the ramp, Morty. They love the slow ramp. It really gets their dicks hard",
    "Morty, you gotta flip 'em off. I told them it means 'peace among worlds.' How hilarious is that!",
    "Listen, if the situation keeps on darkening, then you gotta do yourself a favor and pop by Pirates Of The Pancreas. I mean, the top priority is to, you know, get you guys out of there, but, I mean, if that becomes impossible then you gotta treat yourself.",
    "Jerry: Rick, I don't like glowing rocks in the kitchen trash!\n\nRick: Well, I don't like your unemployed genes in my grandchildren, Jerry, but life is made of little concessions.",
    "Yeah, well, tough titties.",
    "Morty, I'm a drunk, not a hack.",
    "You got some of that mermaid puss.",
    "60 for the resonator, and my grandson wants the sex robot.",
    "Jerry: It sounds like you're about to say Jacob is your lover.\n\nLeonard Smith: No, no, no. Jacob is your mother's lover. I watch them. Sometimes from a chair, sometimes from a closet. Almost always dressed as Superman.",
    "Morty: If you could get out that whole time why didn't you?\n\nRick: Because I waited until I was certain it was what I wanted to do, Morty! That's the difference between you and me: I'm certain, and you're a walking burlap sack filled with turds.",
    "Put a saddle on your universe. Let it kick itself out.",
    "Lick, lick, lick my balls! Ha ha ha, yeah!",
    "I'm Mr. Meeseeks! Look at me!",
    "I can't wait to watch your adventure lay a huge fart.",
    "I masturbated to an extra curvy piece of driftwood the other day!",
    "And then we're gonna go on even more adventures after that, Morty. And you're gonna keep your mouth shut about it, Morty! Because the world is full of idiots that don't understand what's important, and they'll tear us apart, Morty! But if you stick with me, I'm gonna accomplish great things, Morty, and you're gonna be part of 'em. And together we're gonna run around, Morty, we're gonna- do all of kinds of wonderful things, Morty. Just you and me, Morty.",
    "Morty: And also, knock next time, you know? I mean, I'm sitting in here, I'm fourteen! I got a computer in here, you know?\n\nJerry: Oh, I, uh... I think I understa—\n\nMorty: You know, you're really playing with fire when you burst in here like that, man.\n\nJerry: I get it. Say no more.\n\nMorty: I mean one of these days, you know, you're gonna—you're gonna—you're gonna end up seeing something.",
    "Rick: Have you acquired creepy specific old stuff from a mysterious antique or thrift store that gives you powers, but fucks with you in unforeseeable ways? Bring it to 'Curse Purge Plus'! I-I use science to un-curse the items for cash, and you get to keep the powers. This guy got mysterious sneakers to make him run faster, but guess what? He would've had to run until he died, making them worthless. I removed the curse, making them worth, like, I don't know, $8 million? See you at the Olympics. This eerily intelligent doll was threatening to murder its family. Now it does their taxes.\n\nDoll: Everything's deductible.\n\nRick: Don't pay for cool stuff with your soul. Pay for it with money. You know, like how every store in the world works?",
    "[they both exchange kisses, upping their sexual arousal]\n\nUnity: Yes, Rick, yes! Yes, yes!\n\nRick: Wait, wait, stop! H-Hold it! Not like this. We need a hang glider, and a crotchless Uncle Sam costume, and I want the entire field of your largest stadium covered end to end with naked redheads, and I want the stands packed with every man that remotely resembles my father.",
    "Can somebody just let me out of here? If I die in a cage I lose a bet.",
    "Rick: When's the last time you got laid, 'pers?\n\nBirdperson: It has been a... challenging mating season for Birdperson.",
    "How many of these are just horrible mistakes I made? I mean, maybe I'd stop making so many if I let myself learn from them.",
    "Beth: Sorry Jerry, you're real.\n\nJerry: [crying] I'm a parasite!\n\nBeth: Yeah... but you're real.",
    "This seems like a good time for a drink, and a cold, calculated speech with sinister overtones. A speech about politics, about order, brotherhood, power... but speeches are for campaigning. Now is the time for action.",
    "See? Our cup runneth over. Now, who wants to go shopping for a brand-new motherfuckin' world?! All right!",
    "Morty: Can you fly a Black Hawk?\n\nMr. President: Can the pope's **** fit through a donut?\n\nMorty: Eh... I'm not sure?\n\nMr. President: Exactly!",
    "I love watching bukkake. I mean, like, I don't know if I would personally ever do it.",
    "Uncertainty is inherently unsustainable. Eventually, everything either is or isn't.",
    "SHUT THE FUCK UP ABOUT MOONMEN! This isn't a musical number! This is a fucking... operation, we gotta be cool and fucking lay low.",
    "I don't know, maybe you matter so little that I like you. Or maybe it makes you matter. Maybe I love you. Maybe something about your mother. Don't jump a gift shark in the mouth.",
    "You're the little brother. You're not the cause of your parents' misery, you're just a symptom of it.",
    "Bloom: Anatomy Park's greatest attraction, young man, isn't the music or the food or the... Pirates of the Pancreas.\n\nRick: 'Watch it!'",
    "Meh, try not to worry about it, Morty. You're a good kid. And there's not a premium on that right now, but you'll be getting girls sometime after Brad's out of shape.",
    "Beth: Sweetie, is your shirt on backwards?\n\nJerry: ...Yeah! I like it this way. I'm not stupid!\n\nRick: Man that guy is the Redgrin Grumbholt of pretending he knows what's going on.",
    "SCREW YOU, RICK! I'LL PURGE YOU TOO, YOU OLD... \"RICKETY\" PIECE OF CRAP! THIS HAS BEEN A LONG TIME COMING! I'M GONNA RIP YOUR FUCKING GUTS OUT AND SMEAR 'EM ALL OVER YOUR FACE! I AIN'T TAKING NO SH-AAAHH!!",
    "We're miserable Morty! There's a mandatory curfew, their weird calendar made me 47, and they've weaponized the Eiffel tower!",
    "They named a holiday after me. Ricksgiving. They teach kids about me in school!",
    "You guys, are the fucking worst! Your gods are a lie! Fuck you, fuck nature and fuck trees!",
    "Yes, I will! That's right, assholes! Take my penis. Take it all!! And tell Shrimply Pibbles that when the galaxy came calling, Jerry Smith from Earth didn't flinch!",
    "Having a family doesn’t mean that you stop being an individual. You know the best thing you can do for the people that depend on you? Be honest with them, even if it means setting them free.",
    "It's not the same, Summer! Lincler's a crazed maniac. He's just a misguided effort of mine to create a morally neutral super-leader by combining the DNA of Adolf Hitler and Abraham Lincoln. Turns out that ehh-it just adds up to a lame, weird... loser.",
    "Bird Person: Morty, do you know what wubba lubba dub dub means?\n\nMorty: Oh, that's just Rick's stupid nonsense catchphrase.\n\nBird Person: It's not nonsense at all. In my people's tongue, it means, I am in great pain. Please help me.",
    "Listen, Morty, I hate to break it to you, but what people call 'love' is just a chemical reaction that compels animals to breed. It hits hard, Morty, then it slowly fades, leaving you stranded in a failing marriage. I did it. Your parents are gonna do it. Break the cycle, Morty. Rise above. Focus on science.",
    "So, in conclusion, you're both equally mercurial, overly sensitive, clingy, hysterical bird-brain homunculi. And I honestly can't even tell the two of you apart half the time because I don't go by height or age, I go by amount of pain in my ass—which makes you both identical.",
    "I've got an emo streak. It's part of what makes me so rad.",
    "All this time, you've been thinking, 'What if that loser Jerry hadn't talked me out of the abortion?' Well, now you know, you'd be a doctor. Whoop-dee-doo. You'd also be drinking wine, alone in a house full of exotic birds. And I'd be on DiCaprio's yacht, banging Kristen Stewart!",
    "Morty: You're talking about Inception?\n\nRick: That's right, Morty! This is gonna be a lot like that, except y'know, it's gonna me-beh... make sense.\n\nMorty: Inception made sense!\n\nRick: You don't have to try and impress me, Morty!",
    "Yeah motherfucker yeah get it get some, right up your fucking bitch ass you fuck! Guess who just discovered a new element! Think you could do that Morty? You think anyonne but me could do it ever in a billion years? Do you think if God existed he could do it? The answer is no. If God exists its fucking me!",
    "Huntin' a vampire with my grandkids!! FUCK!! TINY RI-I-ICK!!!",
    "Summer: You know you're kind of a dick, right?\n\nRick's Computer: My function is to 'keep Summer safe', not 'keep Summer being, like, totally stoked about, like, the general vibe, and stuff'. That's you, that's how you talk.",
    "And that's why I always say, 'shum-shum-schlippety-dop!'",
    "Get Schwifty.",
    "Wubba-lubba-dub-dub!",
    "Rubber baby bubby bunkers!",
    "Pichael Thompson: And then they found out I was attached along for the ride and they said, 'Ah, shit. Well, just fuck it, call him Pichael.'\n\nMichael Thompson: [throws papers at Pichael's face] Fuck you, Pichael! You're a fucking piece of shit!",
    "That's right, baby. A lot of people would pay top dollar to decimate the population. I'll take the highest bidder—Al-Qaeda, North Korea, Republicans, shriners, balding men that work out, people on the Internet that are only turned on by cartoons of Japanese teenagers. Anything is better than working for you, you pompous, negligent, iTunes-gift-card-as-a-holiday bonus-giving mother—",
    "Right, yeah, like nothing shady ever happened in a fully furnished office? You ever hear about Wall Street, Morty? Y-Y-Y'know what those guys do i-in-in their fancy boardrooms? They take their balls and they dip 'em in cocaine and wipe 'em all over each other—y'know, Grandpa goes around and he does his business in public, because Grandpa isn't shady.",
    "Morty, sit here. Summer, you sit here. Now, listen—I know the two of you are very different from each other in a lot of ways, but you have to understand that as far as Grandpa's concerned, you're both pieces of shit! Yeah. I can prove it mathematically. Actually, l-l-let me grab my whiteboard. This has been a long time coming, anyways.",
    "We're the only fehh-friends we got, Morty! It's just Rick and Morty! Ruh-ick and Morty and their adventures, Morty! Rick and Morty forever and forever, 100 years, Rick and Morty's things! Me and Rick and Morty running around and... Rick and Morty time! All day long, forever... all- a hundred days! Rick and Morty forever a hundred times!",
    "Well then get your shit together, get it all together and put it in a back pack, all your shit, so it's together. And if you gotta take it some where, take it somewhere, you know, take it to the shit store and sell it, or put it in the shit museum. I don't care what you do, you just gotta get it together.\n\nGet your shit together.",
    "Well then get your shit together, get it all together, and put it in a backpack, all your shit, so it’s together.\n\n[pause] \n\nAnd if you gotta take it somewhere, take it somewhere, you know. Take it to the shit store and sell it, or put it in the shit museum. I don’t care what you do, you just gotta get it together.\n\n \n\n[pause]\n\n \n\nGet your shit together.",
    "Mr. Beauregard: Ah, Master Rick, remember when you weren't going to shoot me?\n\nRick: [shoots Mr. Beauregard in the face] I guess Iiii did the butler! Hahaaa! Does that, does that scan?\n\nGhost in a Jar: Oh, I-I get it. It's a play on 'the butler did it.'\n\nRick: Thanks Ghost in a Jar. You always were good at pointing out potentially obscure comedy.",
    "Shrimply Pibbles: I've dwelt among the humans. Their entire culture is built around their penises. It's funny to say they are small. It's funny to say they are big. I've been at parties where humans held bottles, pencils, thermoses in front of themselves and called out, 'Hey, look at me. I'm Mr. So-and-So Dick. I've got such-as-such for a penis.' I never saw it fail to get a laugh.\n\nJerry: All right! That's enough! You guys are talking about my species! We understand genocide! We do it sometimes!",
    "Jerry: What' you doing? Watching some tv, playing on your phone?\n\nSummer: Is that a real question?\n\nJerry: Just making conversation.\n\nSummer: Are you? What part of that gives me anything to work with? My choice is to: say nothing, be sarcastic, or bark \"yes\" like a trained animal. It's not a conversation; you're holding me verbally hostage.",
    "Because I don't respect therapy. Because I'm a scientist. Because I invent, transform, create, and destroy for a living, and when I don't like something about the world, I change it. And I don't think going to a rented office in a strip mall to listen to some agent of averageness explain which words mean which feelings has ever helped anyone do anything. I think it's helped a lot of people get comfortable and stop panicking, which is a state of mind we value in the animals we eat, but not something I want for myself. I'm not a cow. I'm a pickle. When I feel like it. So... you asked.",
    'Rick: No, "Steve" put that memory in your brain so he could live in your house, eat your food and multiply. We could be infested with these things. So, we got to keep an eye out for any zany, wacky characters that pop up.\n\nMr. Poopybutthole: Oooohwee! Whatever you want, Rick, we\'re here to help!\n\nRick: Thanks, Mr. Poopybutthole. I always could count on you.',
    "Morty: You have a whole planet... sitting around making your power for you?! That's slavery!\n\nRick: It's society! They work for each other, Morty. They pay each other, they buy houses, they get married and make children that replace them when they get too old to make power.\n\nMorty: That just sounds like slavery with extra steps!\n\nRick: Ooh-la-la, someone's gonna get laid in college.",
    "President: Here's the adventure: some kind of alien goo-ga has infested the Kennedy Sex Tunnels. I want it hunted down and taken out.\n\nMorty: Kennedy Sex Tunnels?\n\nPresident: Naturally you'll forget you saw them, along with, in order of national embarrassment: the Truman Cocaine Lounge, the McKinley Hooker Dump, and the Lincoln Slave Colosseum. He didn't free them all. And let me know when you're done",
    "Listen, Jerry, I don’t want to overstep my bounds or anything. It’s your house. It’s your world. You’re a real Julius Caesar, but I’ll tell you some, tell you how-how I feel about school, Jerry. It’s a waste of time, a bunch of people running around, bumping into each other. G-guy up front says, “two plus two.” The people in the back say, “four.” Then the bell rings, and they give you a carton of milk and a piece of paper that says you can take a dump or something. I mean, it’s—it’s not a place for smart people, Jerry, and I know that’s not a popular opinion, but it’s my two cents on the issue.",
    "'I took your family'? Who do you think had taken more from them when you shot 20 CCs of liquid dreamkiller into my daughter? She was Rick's daughter, Jerry! She had options! That all ended because she felt sorry for you. You act like prey, but you're a predator! You use pity to lure in your victims! That's how you survive! I survive cause I know everything, that snake survives because children wander off, and you survive 'cause people think 'Ooh, this poor piece of shit, he never gets a break! I can't stand the deafening silent wails of his wilting soul! I guess I'll hire him or marry him!'",
    "An-and I-I-I'll go out and I'll find some more of that Mulan Szechuan teriyaki dipping sauce, Morty! Th-b-because that's what this is all about, Morty! Th-that's my one-armed man! I'm not driven by avenging my dead family, Morty, that was fake! I-I-I'm driven by finding that McNugget sauce! I want that Mulan McNugget sauce, Morty! That's my series arc, Morty! If it takes nine seasons, I want my McNugget... dipping sauce Szechuan sauce, Morty! That's what's gon-it's gonna take us all the way to the end, Morty!"
  ],
  authors: [
    "Morty Jr.  (Richard Christy)",
    "Party-Goer ",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Mr. Meeseeks  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Beth Smith (voice)  (Sarah Chalke)",
    "Evil Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Tammy  (Cassie Steele)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Mr. Meeseeks  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Pichael Thompson ",
    "Poncho  (Gary Anthony Williams)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Morty Smith  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Jerry Smith (voice)  (Chris Parnell)",
    "Summer Smith (voice)  (Spencer Grammer)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez / Morty Smith (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)",
    "Rick Sanchez (voice)  (Justin Roiland)"
  ]
};
